command:
  - "python"
  - "-m"
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: LAKEBASE_PROJECT_ID
    value: "lakebase-lab-logan-rupert"
  - name: LAKEBASE_BRANCH_ID
    value: "production"

resources:
  - name: lakebase-db
    type: postgres
